FROM tomcat:9.0-jdk17-temurin

# Clean default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your JSP files
COPY web /usr/local/tomcat/webapps/ROOT

# Copy compiled .class files (from build/classes)
COPY build/classes /usr/local/tomcat/webapps/ROOT/WEB-INF/classes

EXPOSE 8080

CMD ["catalina.sh", "run"]
